# Generated by Django 6.0.3 on 2026-09-06 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active Investigation'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('FORENSIC_IMAGE', 'Forensic Disk Image (.img/.raw)'), ('PHYSICAL_DEVICE', 'Physical Storage Device'), ('FILE_DIRECTORY', 'File Directory'), ('TEST_MEDIA', 'Synthetic Test Media')], default='FORENSIC_IMAGE', max_length=30)),
                ('file_path', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acquired_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_sources', to='forensic.case')),
            ],
        ),
        migrations.CreateModel(
            name='ChainOfCustodyEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=200)),
                ('object_description', models.CharField(max_length=255)),
                ('recorded_hash', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='forensic.case')),
                ('evidence_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forensic.evidencesource')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
