# Generated by Django 6.0.3 on 2026-09-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDevice',
            fields=[
                ('device_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('capacity_bytes', models.BigIntegerField(default=0)),
                ('interface_type', models.CharField(choices=[('SATA', 'SATA Interface'), ('NVME', 'NVMe Interface'), ('USB', 'USB Flash / External'), ('SD', 'SD / MicroSD Card'), ('VIRTUAL', 'Virtual Disk / Image'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('media_type', models.CharField(choices=[('HDD', 'Hard Disk Drive (Magnetic)'), ('SATA_SSD', 'SATA Solid State Drive'), ('NVME_SSD', 'NVMe Solid State Drive'), ('USB_FLASH', 'USB Flash Storage'), ('SD_CARD', 'SD Memory Card'), ('TEST_IMAGE', 'Synthetic Test Image')], default='HDD', max_length=20)),
                ('filesystem', models.CharField(blank=True, max_length=50)),
                ('removable', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('detected_capabilities', models.JSONField(blank=True, default=dict)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy / PASSED'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical Failure'), ('UNKNOWN', 'Unknown')], default='HEALTHY', max_length=20)),
                ('mount_point', models.CharField(blank=True, max_length=255)),
                ('is_demo_device', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
