# Generated by Django 6.0.3 on 2026-09-06 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('SANITIZATION', 'Sanitization Operation'), ('FILE_ERASURE', 'File Erasure Operation'), ('RECOVERY_FILE', 'Recovered File Verification'), ('EVIDENCE', 'Evidence Image Hashing')], max_length=25)),
                ('target_id', models.CharField(max_length=100)),
                ('verification_method', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('PARTIAL', 'PARTIAL'), ('NOT_VERIFIABLE', 'NOT VERIFIABLE')], default='NOT_VERIFIABLE', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
