# Generated by Django 6.0.3 on 2026-09-06 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation_id', models.CharField(max_length=100)),
                ('ledger_type', models.CharField(choices=[('LOCAL_IMMUTABLE', 'Local Immutable Hash Ledger'), ('ETHEREUM_SIMULATED', 'Ethereum Smart Contract Adapter'), ('SOLANA_SIMULATED', 'Solana Forensic Program Adapter'), ('HYPERLEDGER_SIMULATED', 'Hyperledger Fabric Adapter')], default='LOCAL_IMMUTABLE', max_length=30)),
                ('transaction_id', models.CharField(max_length=100)),
                ('report_hash', models.CharField(blank=True, max_length=64)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified Immutable'), ('TAMPERED', 'Tamper Detected'), ('PENDING', 'Pending Confirmation')], default='VERIFIED', max_length=20)),
            ],
        ),
    ]
