# Generated by Django 6.0.3 on 2026-09-06 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileErasureOperation',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_path', models.CharField(max_length=500)),
                ('item_type', models.CharField(choices=[('SINGLE_FILE', 'Single File'), ('DIRECTORY', 'Directory / Folder'), ('BATCH', 'Batch Files')], default='SINGLE_FILE', max_length=20)),
                ('total_files', models.IntegerField(default=1)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('erasure_method', models.CharField(choices=[('ZERO_OVERWRITE', 'Single Pass Zero Fill'), ('MULTI_PASS_RANDOM', '3-Pass Pseudo-Random Overwrite'), ('GUTMANN_SIMULATION', 'Gutmann Standard Simulation'), ('UNLINK_ONLY', 'Unlink / Truncate Only')], default='ZERO_OVERWRITE', max_length=30)),
                ('execution_mode', models.CharField(choices=[('DEMO_MODE', 'Demo Mode'), ('SAFE_TEST_MODE', 'Safe Test Sandbox Mode'), ('REAL_MODE', 'Real File System Erasure')], default='DEMO_MODE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('verification_status', models.CharField(default='NOT_VERIFIABLE', max_length=20)),
                ('operation_hash', models.CharField(blank=True, max_length=64)),
                ('inventory_metadata', models.JSONField(blank=True, default=dict)),
                ('limitation_warnings', models.JSONField(blank=True, default=list)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
