# Generated by Django 6.0.3 on 2026-09-06 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forensic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryOperation',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_types', models.JSONField(default=list, help_text="Selected file extensions e.g. ['jpg', 'pdf', 'docx']")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCANNING', 'Scanning Evidence Image'), ('CARVING', 'Carving & Extraction'), ('VALIDATING', 'Validating Recovered Candidates'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_scanned_bytes', models.BigIntegerField(default=0)),
                ('candidates_found', models.IntegerField(default=0)),
                ('valid_files_count', models.IntegerField(default=0)),
                ('operation_hash', models.CharField(blank=True, max_length=64)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_operations', to='forensic.case')),
                ('evidence_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_operations', to='forensic.evidencesource')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveredFile',
            fields=[
                ('recovery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('detected_type', models.CharField(max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sector_offset', models.BigIntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0, help_text='Analytical score 0 to 100')),
                ('carving_method', models.CharField(default='HEADER_FOOTER_MATCH', max_length=100)),
                ('validation_status', models.CharField(choices=[('VALID', 'Valid Structure & Decoded'), ('PARTIALLY_VALID', 'Partially Valid / Truncated'), ('CORRUPTED', 'Corrupted Header/Payload'), ('INVALID', 'Invalid / False Positive'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('output_path', models.CharField(max_length=500)),
                ('classification', models.CharField(choices=[('IMAGE', 'Image File'), ('DOCUMENT', 'Document / PDF / Office'), ('AUDIO', 'Audio File'), ('VIDEO', 'Video File'), ('ARCHIVE', 'Archive / ZIP'), ('TEXT', 'Text Document'), ('EXECUTABLE', 'Executable / Binary'), ('OTHER', 'Other Artifact')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovered_files', to='forensic.case')),
                ('evidence_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic.evidencesource')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovered_files', to='recovery.recoveryoperation')),
            ],
        ),
    ]
