# Generated by Django 6.1.1 on 2026-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveredfile',
            name='byte_offset',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='deleted_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='fragment_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='fragments_missing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='original_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='reconstruction_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='recovery_source',
            field=models.CharField(default='Signature Carving', max_length=100),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='sector_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recoveredfile',
            name='validation_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recoveryoperation',
            name='current_phase',
            field=models.CharField(default='Completed', max_length=100),
        ),
        migrations.AddField(
            model_name='recoveryoperation',
            name='failure_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recoveryoperation',
            name='methods_attempted',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recoveryoperation',
            name='methods_completed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recoveryoperation',
            name='methods_skipped',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recoveryoperation',
            name='progress_percent',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='recoveryoperation',
            name='recovery_mode',
            field=models.CharField(choices=[('QUICK', 'Quick Recovery (Filesystem Metadata)'), ('DEEP', 'Deep Recovery (Metadata + Carving + Validation)'), ('MAXIMUM', 'Maximum Recovery (Metadata + Carving + Fragments + Fusion)')], default='DEEP', max_length=20),
        ),
    ]
