# Generated by Django 6.0.3 on 2026-09-06 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.CharField(blank=True, max_length=45)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('previous_event_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('event_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
