# Generated by Django 6.0.3 on 2026-09-06 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forensic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('SANITIZATION_CERTIFICATE', 'Drive Sanitization Certificate'), ('FILE_ERASURE_REPORT', 'File & Directory Erasure Report'), ('FORENSIC_RECOVERY_REPORT', 'Forensic File Carving & Recovery Report'), ('EVIDENCE_INTEGRITY_REPORT', 'Evidence Integrity Report'), ('CHAIN_OF_CUSTODY_REPORT', 'Chain of Custody Report'), ('AUDIT_REPORT', 'System Audit & Tamper Log Report')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
                ('report_hash', models.CharField(blank=True, max_length=64)),
                ('format', models.CharField(choices=[('PDF', 'PDF Document'), ('HTML', 'HTML Web Page'), ('JSON', 'JSON Data Export')], default='PDF', max_length=10)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forensic.case')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
