# Generated by Django 6.0.3 on 2026-09-06 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('forensic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanitizationOperation',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('NIST_CLEAR', 'NIST SP 800-88 Clear (Logical Overwrite)'), ('NIST_PURGE', 'NIST SP 800-88 Purge (Device Sanitize Command)'), ('CRYPTOGRAPHIC_ERASE', 'Cryptographic Erase (CE / Sanitize)'), ('DOD_3_PASS', 'DoD 5220.22-M (3-Pass Simulation)'), ('ZERO_FILL', 'Single-Pass Zero Fill'), ('RANDOM_PASS', 'Random Data Pass')], default='NIST_CLEAR', max_length=35)),
                ('execution_mode', models.CharField(choices=[('DEMO_MODE', 'Demo Mode (Safe Synthetic Image)'), ('SAFE_TEST_MODE', 'Safe Test Mode (Sandbox File/Drive)'), ('REAL_MODE', 'Real Mode (Destructive Hardware Access)')], default='DEMO_MODE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('verification_status', models.CharField(choices=[('PASS', 'PASS (Verification Succeeded)'), ('FAIL', 'FAIL (Verification Failed)'), ('PARTIAL', 'PARTIAL Verification'), ('NOT_VERIFIABLE', 'NOT VERIFIABLE')], default='NOT_VERIFIABLE', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('report_path', models.CharField(blank=True, max_length=500)),
                ('operation_hash', models.CharField(blank=True, max_length=64)),
                ('assurance_level', models.CharField(default='CLEAR', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forensic.case')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitization_operations', to='devices.storagedevice')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
