# Generated by Django 6.0.3 on 2026-09-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizationoperation',
            name='bytes_processed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanitizationoperation',
            name='current_stage',
            field=models.CharField(default='INITIALIZING', max_length=50),
        ),
        migrations.AddField(
            model_name='sanitizationoperation',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanitizationoperation',
            name='status_message',
            field=models.CharField(default='Initializing sanitization...', max_length=255),
        ),
        migrations.AddField(
            model_name='sanitizationoperation',
            name='total_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sanitizationoperation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INITIALIZING', 'Initializing'), ('DETECTING_DEVICE', 'Detecting Device'), ('CHECKING_CAPABILITIES', 'Checking Capabilities'), ('PREPARING', 'Preparing'), ('SANITIZING', 'Sanitizing'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25),
        ),
    ]
