# Generated by Django 6.1.1 on 2026-09-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('INVESTIGATOR', 'Forensic Investigator'), ('OPERATOR', 'Sanitization Operator'), ('VIEWER', 'Auditor / Viewer')], default='ADMIN', max_length=20),
        ),
    ]
